version: "3.5"

services:
  newmobofficeapp:
    build:
      context: "."
      args:
        UID: ${UID}
    container_name: newmobofficeapp
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html

  newmob_mysql_db:
    image: mysql:5.7
    container_name: newmob_mysql_db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
