version: '3'
services:
  prod_strapi:
    image: node:14-alpine
    volumes:
      - ./backend:/home/node/app
    environment:
      - DATABASE_HOST=mysql_database
      - DATABASE_NAME=newmob-db
      - DATABASE_USERNAME=newmobuser
      - DATABASE_PASSWORD=qJ4dRwP+FM9fBDq&
    working_dir: /home/node/app
    user: node
    command: yarn run strapi
  
  prod_frontend:
    image: node:14-alpine
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
    user: node
    environment:
      - NUXT_HOST=0.0.0.0
    networks:
      - nginx_proxy
      - default      
    command: yarn start

networks:
  nginx_proxy:
    external: true
    name: nginx_proxy_manager_default
